liip_imagine:
    driver: gd
    resolvers:
       default:
          web_path: ~
    filter_sets:
       admin_thumb:
              quality: 90
              filters:
                  thumbnail: { size: [260, 180], mode: outbound }
       gallery_thumb:
              quality: 90
              filters:
                  thumbnail: { size: [120, 90], mode: outbound }
       article_thumb:
              quality: 90
              filters:
                  thumbnail: { size: [200, 100], mode: outbound }
       article_full:
              quality: 90
              filters:
                  thumbnail: { size: [500, 800], mode: inset }
       gallery_thumb:
              quality: 90
              filters:
                  thumbnail: { size: [160, 120], mode: outbound }
       gallery_full:
              quality: 90
              filters:
                  thumbnail: { size: [1900, 1200], mode: inset }
       newsThumb:
            quality: 90
            filters:
                relative_resize: { widen: 170 }
