parameters:
    web.root_dir: "%kernel.root_dir%/../web"
    tmp_files_path: /uploads/tmp
    files_path: /uploads/files

imports:
    - { resource: security.yml }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: TheCodeine\UserBundle\Entity\User

assetic:
    debug:              "%kernel.debug%"
    use_controller:     false
    ruby: ~
    filters:
        cssrewrite: ~
        sass:
            apply_to: "\.s[ac]ss$"
            bin: "%sass_bin%"

a2lix_translation_form:
    locales: [pl, en]
    templating: "TheCodeineAdminBundle::_partials/_form/_theme.html.twig"

the_codeine_editor:
    autoinclude: true

stof_doctrine_extensions:
    default_locale: pl
    persist_default_translation: false
    translation_fallback: true
    orm:
        default:
            timestampable: true
            sluggable: true
            translatable: true

knp_paginator:
    page_range: 5
    template:
        pagination: "TheCodeineAdminBundle:_partials/_pagination.html.twig"

knp_gaufrette:
    adapters:
        attachment_adapter:
            local:
                directory: "%kernel.root_dir%/../web/files"

    filesystems:
        attachment_fs:
            adapter:    attachment_adapter
    stream_wrapper:
        protocol: http

vich_uploader:
    db_driver: orm
    storage: gaufrette
    mappings:
        news_attachments:
            uri_prefix: /files
            upload_destination: attachment_fs
            namer: vich_uploader.namer_origname

jms_translation:
    configs:
        app:
            dirs: ["%kernel.root_dir%", "%kernel.root_dir%/../src"]
            output_dir: "%kernel.root_dir%/Resources/translations"
            ignored_domains: [routes]
            excluded_dirs: [cache, data, logs]

liip_imagine:
    driver: gd
    resolvers:
        default:
            web_path: ~
    filter_sets:
        tuna_admin_thumb:
            quality: 90
            filters:
                upscale: { min: [280, 196] }
                thumbnail: { size: [280, 196], mode: outbound }
        tuna_gallery_thumb:
            quality: 90
            filters:
                upscale: { min: [160, 120] }
                thumbnail: { size: [160, 120], mode: outbound }
        tuna_gallery_full:
            quality: 90
            filters:
                thumbnail: { size: [1900, 1200], mode: inset }

bazinga_js_translation:
    default_domain: tuna_admin
    active_domains:
        - tuna_admin

accelerator_cache:
    host: %the_codeine_admin.host%
    web_dir: %kernel.root_dir%/../web
    mode: curl
