liip_imagine:
    driver: gd
    resolvers:
        default:
            web_path: ~
    filter_sets:
        tuna_admin_thumb:
            quality: 90
            filters:
                thumbnail: { size: [260, 180], mode: outbound }
        tuna_gallery_thumb:
            quality: 90
            filters:
                thumbnail: { size: [160, 120], mode: outbound }
        tuna_gallery_full:
            quality: 90
            filters:
                thumbnail: { size: [1900, 1200], mode: inset }
