_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# IMAGE Route
thecodeine_image:
    resource: "@TheCodeineImageBundle/Resources/config/routing.yml"

# PAGE Route
thecodeine_page_show:
    path: /{_locale}/page/{id}
    defaults:  { _controller: TheCodeineAdminBundle:Page:show }
    requirements:
        id:  \d+

thecodeine_page_create:
    path: /admin/page/create
    defaults:  { _controller: TheCodeineAdminBundle:Page:create }

thecodeine_page_list:
    path: /admin/page/list
    defaults:  { _controller: TheCodeineAdminBundle:Page:list }

thecodeine_page_edit:
    path: /admin/page/{id}/edit
    defaults:  { _controller: TheCodeineAdminBundle:Page:edit, id: 0 }
    requirements:
        id:  \d+

thecodeine_page_delete:
    path: /admin/page/{id}/delete
    defaults:  { _controller: TheCodeineAdminBundle:Page:delete, id: 0 }
    requirements:
        id:  \d+

# ADMIN Route
thecodeine_admin_homepage:
    path: /admin/
    defaults: { _controller: TheCodeineAdminBundle:Admin:index }

# SECURITY
fos_user_security_login:
    path: /login
    defaults: { _controller: TheCodeineAdminBundle:Security:login }

fos_user_security_check:
    path: /login_check
    defaults: { _controller: TheCodeineAdminBundle:Security:check }
    methods:  [POST]

fos_user_security_logout:
    path: /logout
    defaults: { _controller: TheCodeineAdminBundle:Security:logout }
