_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

tuna_user:
    resource: "@TheCodeineUserBundle/Resources/config/routing.yml"

tuna_page:
    resource: "@TheCodeineAdminBundle/Controller/PageController.php"
    type:     annotation
    prefix:   /admin/

tuna_file:
    resource: "@TheCodeineFileBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /admin/

tuna_menu_admin:
    resource: "@TheCodeineAdminBundle/Controller/MenuController.php"
    type:     annotation
    prefix:   /admin/

tuna_news:
    resource: "@TheCodeineAdminBundle/Controller/NewsController.php"
    type:     annotation
    prefix:   /admin/

tuna_translations:
    resource: "@TheCodeineTranslationBundle/Resources/config/routing.yml"
    prefix:   /admin/

tuna_category:
    resource: "@TheCodeineAdminBundle/Controller/CategoryController.php"
    type:     annotation
    prefix:   /admin/

tuna_admin_homepage:
    path: /admin/
    defaults: { _controller: TheCodeineAdminBundle:Admin:index }
