_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# SECURITY
fos_user_security_login:
    path: /login
    defaults: { _controller: TheCodeineAdminBundle:Security:login }

fos_user_security_check:
    path: /login_check
    defaults: { _controller: TheCodeineAdminBundle:Security:check }
    methods:  [POST]

fos_user_security_logout:
    path: /logout
    defaults: { _controller: TheCodeineAdminBundle:Security:logout }

# CATEGORY Route
tuna_category:
    resource: "@TheCodeineCategoryBundle/Resources/config/routes.yml"
    prefix: /admin

tuna_category_list:
    path: /admin/category/list
    defaults:  { _controller: TheCodeineAdminBundle:Category:list }

tuna_category_edit:
    path: /admin/category/{id}/edit
    defaults:  { _controller: TheCodeineAdminBundle:Category:edit }
    requirements:
        id:  \d+

# IMAGE Route
tuna_image:
    resource: "@TheCodeineImageBundle/Resources/config/routing.yml"

# NEWS Route
tuna_news:
    resource: "@TheCodeineNewsBundle/Resources/config/routing.yml"

tuna_news_list:
    pattern:  /admin/news/list
    defaults: { _controller: TheCodeineAdminBundle:News:list }

tuna_news_show:
    pattern: /{_locale}/news/{id}
    defaults: { _controller: TheCodeineAdminBundle:News:show, id: 0 }
    requirements:
        id: \d+

tuna_news_create:
    pattern: /admin/news/create
    defaults: { _controller: TheCodeineAdminBundle:News:create }

tuna_news_edit:
    pattern: /admin/news/{id}/edit
    defaults: { _controller: TheCodeineAdminBundle:News:edit, id: 0 }
    requirements:
        id: \d+

tuna_news_attachment_add:
    pattern: /admin/news/{id}/attachment/add
    defaults: { _controller: TheCodeineAdminBundle:News:addAttachment, id: 0 }
    requirements:
        id: \d+

tuna_news_delete:
    pattern: /admin/news/{id}/delete
    defaults: { _controller: TheCodeineAdminBundle:News:delete }
    requirements:
        id: \d+

# PAGE Route
tuna_page:
    resource: "@TheCodeinePageBundle/Resources/config/routing.yml"

tuna_page_show:
    path: /{_locale}/page/{id}
    defaults:  { _controller: TheCodeineAdminBundle:Page:show }
    requirements:
        id:  \d+

tuna_page_create:
    path: /admin/page/create
    defaults:  { _controller: TheCodeineAdminBundle:Page:create }

tuna_page_list:
    path: /admin/page/list
    defaults:  { _controller: TheCodeineAdminBundle:Page:list }

tuna_page_edit:
    path: /admin/page/{id}/edit
    defaults:  { _controller: TheCodeineAdminBundle:Page:edit, id: 0 }
    requirements:
        id:  \d+

tuna_page_delete:
    path: /admin/page/{id}/delete
    defaults:  { _controller: TheCodeineAdminBundle:Page:delete, id: 0 }
    requirements:
        id:  \d+

# ADMIN Route
tuna_admin_homepage:
    path: /admin/
    defaults: { _controller: TheCodeineAdminBundle:Admin:index }

# TRANSLATIONS Route
JMSTranslationBundle_translate:
    resource: "@JMSTranslationBundle/Controller/ApiController.php"
    type: annotation
    prefix: /admin/translations
    condition: "%enable_translations%"

JMSTranslationBundle_api:
    resource: "@JMSTranslationBundle/Controller/TranslateController.php"
    type: annotation
    prefix: /admin/translations
    condition: "%enable_translations%"

tuna_translations:
    path: /admin/translations
