fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

the_codeine_news:
    resource: "@TheCodeineNewsBundle/Resources/config/routing.yml"

the_codeine_page:
    resource: "@TheCodeinePageBundle/Resources/config/routing.yml"

thecodeine_admin_homepage:
    path: /admin/
    defaults: { _controller: TheCodeineAdminBundle:Admin:index }

thecodeine_admin_category:
    path: /admin/cid/{cid}
    defaults: { _controller: TheCodeineAdminBundle:Admin:category }

thecodeine_admin_category_list:
    path: /admin/category
    defaults: { _controller: TheCodeineAdminBundle:Category:index }