_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# SECURITY
fos_user_security_login:
    path: /login
    defaults: { _controller: TheCodeineAdminBundle:Security:login }

fos_user_security_check:
    path: /login_check
    defaults: { _controller: TheCodeineAdminBundle:Security:check }
    methods:  [POST]

fos_user_security_logout:
    path: /logout
    defaults: { _controller: TheCodeineAdminBundle:Security:logout }

fos_user_change_password:
    path: /admin/change-password
    defaults: { _controller: TheCodeineUserBundle:ChangePassword:changePassword }

tuna_image:
    resource: "@TheCodeineImageBundle/Resources/config/routing.yml"

tuna_page:
    resource: "@TheCodeineAdminBundle/Controller/PageController.php"
    type:     annotation
    prefix:   /admin/

tuna_news:
    resource: "@TheCodeineAdminBundle/Controller/NewsController.php"
    type:     annotation
    prefix:   /admin/

tuna_category:
    resource: "@TheCodeineAdminBundle/Controller/CategoryController.php"
    type:     annotation
    prefix:   /admin/

# ADMIN Route
tuna_admin_homepage:
    path: /admin/
    defaults: { _controller: TheCodeineAdminBundle:Admin:index }

# TRANSLATIONS Route
JMSTranslationBundle_translate:
    resource: "@JMSTranslationBundle/Controller/ApiController.php"
    type: annotation
    prefix: /admin/translations
    condition: "%the_codeine_admin.enable_translations_string%"

JMSTranslationBundle_api:
    resource: "@JMSTranslationBundle/Controller/TranslateController.php"
    type: annotation
    prefix: /admin/translations
    condition: "%the_codeine_admin.enable_translations_string%"

tuna_translations_cache:
    resource: "@TheCodeineTranslationBundle/Controller/CacheController.php"
    type: annotation
    prefix: /admin/translations

tuna_translations:
    path: /admin/translations
    condition: "%the_codeine_admin.enable_translations_string%"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"