fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# IMAGE Route
thecodeine_image:
    resource: "@TheCodeineImageBundle/Resources/config/routing.yml"

# NEWS Route
thecodeine_news_list:
    pattern:  /admin/news/list
    defaults: { _controller: TheCodeineAdminBundle:News:list }

thecodeine_news_show:
    pattern: /{_locale}/news/{id}
    defaults: { _controller: TheCodeineAdminBundle:News:show, id: 0 }
    requirements:
        id: \d+

thecodeine_news_create:
    pattern: /admin/news/create
    defaults: { _controller: TheCodeineAdminBundle:News:create }

thecodeine_news_edit:
    pattern: /admin/news/{id}/edit
    defaults: { _controller: TheCodeineAdminBundle:News:edit, id: 0 }
    requirements:
        id: \d+

thecodeine_news_attachment_add:
    pattern: /admin/news/{id}/attachment/add
    defaults: { _controller: TheCodeineAdminBundle:News:addAttachment, id: 0 }
    requirements:
        id: \d+

thecodeine_news_delete:
    pattern: /admin/news/{id}/delete
    defaults: { _controller: TheCodeineAdminBundle:News:delete }
    requirements:
        id: \d+

# PAGE Route
thecodeine_page_show:
    path: /{_locale}/page/{id}
    defaults:  { _controller: TheCodeineAdminBundle:Page:show }
    requirements:
        id:  \d+

thecodeine_page_create:
    path: /admin/page/create
    defaults:  { _controller: TheCodeineAdminBundle:Page:create }

thecodeine_page_list:
    path: /admin/page/list
    defaults:  { _controller: TheCodeineAdminBundle:Page:list }

thecodeine_page_edit:
    path: /admin/page/{id}/edit
    defaults:  { _controller: TheCodeineAdminBundle:Page:edit, id: 0 }
    requirements:
        id:  \d+

thecodeine_page_delete:
    path: /admin/page/{id}/delete
    defaults:  { _controller: TheCodeineAdminBundle:Page:delete, id: 0 }
    requirements:
        id:  \d+

# ADMIN Route
thecodeine_admin_homepage:
    path: /admin/
    defaults: { _controller: TheCodeineAdminBundle:Admin:index }