_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

the_codeine_user:
    resource: "@TheCodeineUserBundle/Controller/"
    type:     annotation
    prefix:   /

# SECURITY
fos_user_security_login:
    path: /login
    defaults: { _controller: TheCodeineAdminBundle:Security:login }

fos_user_security_check:
    path: /login_check
    defaults: { _controller: TheCodeineAdminBundle:Security:check }
    methods:  [POST]

fos_user_security_logout:
    path: /logout
    defaults: { _controller: TheCodeineAdminBundle:Security:logout }

# IMAGE Route
thecodeine_image:
    resource: "@TheCodeineImageBundle/Resources/config/routing.yml"

# NEWS Route
the_codeine_news:
    resource: "@TheCodeineNewsBundle/Resources/config/routing.yml"

thecodeine_news_show:
    path: /{_locale}/news/{newsType}/{id}
    defaults: { _controller: TheCodeineAdminBundle:News:show, id: 0 }
    requirements:
        id: \d+

thecodeine_news_list:
    path:  /admin/news/{newsType}/list
    defaults: { _controller: TheCodeineAdminBundle:News:list }

thecodeine_news_create:
    path: /admin/news/{newsType}/create
    defaults: { _controller: TheCodeineAdminBundle:News:create }
    defaults: { _controller: TheCodeineAdminBundle:News:create }

thecodeine_news_edit:
    path: /admin/news/{newsType}/{id}/edit
    defaults: { _controller: TheCodeineAdminBundle:News:edit, id: 0 }
    requirements:
        id: \d+

thecodeine_news_attachment_add:
    path: /admin/news/{newsType}/{id}/attachment/add

    defaults: { _controller: TheCodeineAdminBundle:News:addAttachment, id: 0 }
    requirements:
        id: \d+

thecodeine_news_delete:
    path: /admin/news/{newsType}/{id}/delete
    defaults: { _controller: TheCodeineAdminBundle:News:delete }
    requirements:
        id: \d+

# PAGE Route
the_codeine_page:
    resource: "@TheCodeinePageBundle/Resources/config/routing.yml"

thecodeine_page_show:
    path: /{_locale}/page/{id}
    defaults:  { _controller: TheCodeineAdminBundle:Page:show }
    requirements:
        id:  \d+

thecodeine_page_create:
    path: /admin/page/create
    defaults:  { _controller: TheCodeineAdminBundle:Page:create }

thecodeine_page_list:
    path: /admin/page/list
    defaults:  { _controller: TheCodeineAdminBundle:Page:list }

thecodeine_page_edit:
    path: /admin/page/{id}/edit
    defaults:  { _controller: TheCodeineAdminBundle:Page:edit, id: 0 }
    requirements:
        id:  \d+

thecodeine_page_delete:
    path: /admin/page/{id}/delete
    defaults:  { _controller: TheCodeineAdminBundle:Page:delete, id: 0 }
    requirements:
        id:  \d+

# ADMIN Route
thecodeine_admin_homepage:
    path: /admin/
    defaults: { _controller: TheCodeineAdminBundle:Admin:index }
