language: php
php:
    - '5.6'

before_script:
    - phpenv config-add travis.php.ini
    - composer install --prefer-source --no-interaction --optimize-autoloader

script:
    - ./run-tests.sh
    # - ./bin/synchronize_bundles.sh $TRAVIS_BRANCH