services:
    the_codeine_file.manager.file_manager:
        class: TheCodeine\FileBundle\Manager\FileManager
        arguments: ["@filesystem", "%tuna_file_manager%"]

    the_codeine_file.event_listener.file_listener:
        class: TheCodeine\FileBundle\EventListener\FileListener
        arguments:
            - "@the_codeine_file.manager.file_manager"
        tags:
            - { name: doctrine.orm.entity_listener }
