_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

thecodeine_gallery_video_create:
    path: /admin/gallery/{id}/edit
    defaults:  { _controller: TheCodeineGalleryBundle:Gallery:edit, id: 0 }
    requirements:
        id:  \d+

thecodeine_gallery_video_show:
    path: /admin/gallery/{id}/show
    defaults:  { _controller: TheCodeineGalleryBundle:Gallery:show, id: 0 }
    requirements:
        id:  \d+