thecodeine_news_show:
    pattern: /{_locale}/news/{id}
    defaults: { _controller: TheCodeineNewsBundle:News:show, id: 0 }
    requirements:
        id: \d+

thecodeine_news_list:
    pattern:  /admin/news/list
    defaults: { _controller: TheCodeineNewsBundle:News:list }

thecodeine_news_create:
    pattern: /admin/news/create
    defaults: { _controller: TheCodeineNewsBundle:News:create }

thecodeine_news_edit:
    pattern: /admin/news/{id}/edit
    defaults: { _controller: TheCodeineNewsBundle:News:edit, id: 0 }
    requirements:
        id: \d+

thecodeine_news_attachment_add:
    pattern: /admin/news/{id}/attachment/add
    defaults: { _controller: TheCodeineNewsBundle:News:addAttachment, id: 0 }
    requirements:
        id: \d+

thecodeine_news_delete:
    pattern: /admin/news/{id}/delete
    defaults: { _controller: TheCodeineNewsBundle:News:delete }
    requirements:
        id: \d+