tuna_news_show:
    path: /{_locale}/news/{id}
    defaults: { _controller: TheCodeineNewsBundle:News:show, id: 0 }
    requirements:
        id: \d+

tuna_news_list:
    path:  /admin/news/list
    defaults: { _controller: TheCodeineNewsBundle:News:list }

tuna_news_create:
    path: /admin/news/create
    defaults: { _controller: TheCodeineNewsBundle:News:create }

tuna_news_edit:
    path: /admin/news/{id}/edit
    defaults: { _controller: TheCodeineNewsBundle:News:edit, id: 0 }
    requirements:
        id: \d+

tuna_news_attachment_add:
    path: /admin/news/{id}/attachment/add
    defaults: { _controller: TheCodeineNewsBundle:News:addAttachment, id: 0 }
    requirements:
        id: \d+

tuna_news_delete:
    path: /admin/news/{id}/delete
    defaults: { _controller: TheCodeineNewsBundle:News:delete }
    requirements:
        id: \d+
