services:
    tuna.news.factory:
        class: TheCodeine\NewsBundle\Service\NewsFactory
        arguments: ['@doctrine.orm.default_entity_manager']

    tuna.news.param_converter:
            class: TheCodeine\NewsBundle\Request\NewsTypeParamConverter
            arguments: ['@doctrine.orm.default_entity_manager']
            tags:
                - { name: request.param_converter, converter: news, priority: 10 }
